apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- route.yaml



configMapGenerator:
- files:
  - config/custom.conf
  name: connectivity-probe-apache-conf
- files:
  - cgi/index.py
  name: connectivity-probe-cgi
- files:
  - config/config.json
  name: probe-config


commonLabels:
  app.kubernetes.io/component: demo-app
  app.kubernetes.io/part-of: demo-app-platform
namePrefix: team-b1-
