apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: strict-team-b
  namespace: team-b1
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          team: team-b
  policyTypes:
  - Ingress