apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- route.yaml

configMapGenerator:
- files:
  - config/custom.conf
  name: weather-proxy-apache-conf
- files:
  - cgi/index.py
  name: weather-proxy-cgi

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: weather-platform
