apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

configMapGenerator:
  - name: weather-proxy-apache-conf
    files:
      - config/custom.conf
  - name: weather-proxy-cgi
    files:
      - cgi/index.py

commonLabels:
  app.kubernetes.io/part-of: weather-platform
  app.kubernetes.io/component: proxy

# NOTE: Removed disableNameSuffixHash so generated ConfigMaps will have a
# content hash suffix. Any change to the underlying files produces a new
# ConfigMap name, updating the Pod template and triggering an automatic
# Deployment rollout.
