apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-weather
  namespace: weather-proxy
spec:
  podSelector: {}
  egress:
  - to:
    - ipBlock:
        cidr: 203.0.113.0/24
  policyTypes:
  - Egress